webserver/users/urls.py
from django.conf.urls.static import static
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('register/', views.register, name='register'),  # FIX ME
    path('profile/', views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', views.logout, name='logout'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html", post_reset_login=True, success_url="/password-reset/success/"), name='password_reset_confirm'),
    path('password-reset/success/', auth_views.PasswordResetDoneView.as_view(template_name="index.html", extra_context={"alert": "You have successfully changed your password and are now logged in."}), name='password_reset_success'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="users/password_reset.html", email_template_name="users/password_reset_email.html"), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="index.html", extra_context={"alert": "If your email is associated with a registered account, you will receive an email with instructions on how to change your password."}), name='password_reset_done'),
    path('activate/<uidb64>/<token>', views.activate, name='activate')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webserver/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.conf import settings
import os
from lasair.utils import bytes2string
import io
from django.core.validators import FileExtensionValidator


class Profile(models.Model):

    if settings.DEBUG:
        staticRoot = settings.STATICFILES_DIRS[0]
    else:
        staticRoot = settings.STATIC_ROOT

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics', validators=[FileExtensionValidator(allowed_extensions=['gif', 'jpeg', 'jpg', 'png'])])

    with open(staticRoot + '/img/default.jpg', mode='rb') as readFile:
        defaultImage = readFile.read()
        defaultImage = bytes2string(defaultImage)
        image_b64 = models.TextField(blank=True, null=True, default=defaultImage)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)
        imgByteArr = io.BytesIO()
        img.save(imgByteArr, format=img.format)
        self.image_b64 = bytes2string(imgByteArr.getvalue())

webserver/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from crispy_forms.helper import FormHelper
try:
    from captcha.fields import ReCaptchaField
except ImportError:
    from django_recaptcha.fields import ReCaptchaField
try:
    from captcha.widgets import ReCaptchaV3
except ImportError:
    from django_recaptcha.widgets import ReCaptchaV3

from django.conf import settings
from django.core.exceptions import ValidationError


class UserRegisterForm(UserCreationForm):
    captcha = ReCaptchaField(widget=ReCaptchaV3())
    email = forms.EmailField()
    privacy = forms.BooleanField(required=True)
    if getattr(settings, "DEBUG", False) and getattr(settings, "LASAIR_URL", False) == "127.0.0.1":
        captcha.clean = lambda x: True

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'captcha', 'privacy']

    def clean(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            msg = 'A user with that email already exists.'
            self.add_error('email', msg)

        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            msg = 'This username is already taken, please try a different one.'
            self.add_error('username', msg)

        return self.cleaned_data


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']


class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['image']

    def clean(self):
        image = self.cleaned_data.get('image')

        return self.cleaned_data

webserver/users/views.py
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import authenticate, get_user_model
from django.shortcuts import render, redirect
from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages
from rest_framework.authtoken.models import Token
from .forms import UserRegisterForm, ProfileUpdateForm, UserUpdateForm
from django.contrib.auth.decorators import login_required
import sys
from .utils import account_activation_token
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            activateEmail(request, user, form.cleaned_data.get('email'))
            return redirect('index')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except:
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        messages.success(request, "Thank you for verifying your email. Now you can login to your account.")
        return redirect('login')
    else:
        messages.error(request, "Activation link is invalid!")

    return redirect('index')


def activateEmail(request, user, to_email):
    mail_subject = "Activate your Lasair account."
    message = render_to_string("users/email_verification_email.html", {
        'user': user.username,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        "protocol": 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    if email.send():
        messages.success(request, f'We have sent you an email to {to_email}. Please follow the instructions to acivate your Lasair account. Can\'t find the email? Please check your spam folder.')
    else:
        messages.error(request, f'Problem sending email to {to_email}, please check you typed it correctly.')


@login_required
def profile(request):

    token, created = Token.objects.get_or_create(user=request.user)

    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            p_form.save()
            u_form.save()
            messages.success(request, f'Your account has been updated.')
            return redirect('profile')
    else:
        # GET REQUEST
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
        'token': token.key
    }
    return render(request, "users/profile.html", context)


@login_required(redirect_field_name=None)
def logout(request):
    # message user or whatever
    template_name = "users/logout.html"
    context = {
        'username': request.user.username,
        'profile_image': request.user.profile.image_b64
    }
    auth_logout(request)
    return render(request, "users/logout.html", context)
    # return logout(request)

webserver/users/templates/users/email_verification_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}Hi {{ user }},

Please click on the link below to verify your email address and active your Lasair account:{% endblocktranslate %}

https://{{ domain }}{% url 'activate' uidb64=uid token=token %}

{% blocktranslate %}The Lasair team{% endblocktranslate %}
{% endautoescape %}

webserver/users/templates/users/login.html
{% extends "layouts/base-fullscreen.html" %}
{% load widget_tweaks %}
{% block title %} Sign IN {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 d-flex align-items-center justify-content-center">

                <div class="bg-white shadow border-0 rounded border-light p-4 p-lg-5 w-100 fmxw-500 mt-9">
                    <div class="text-center text-md-center mb-4 mt-md-0">
                        {% include "includes/icons/icon.html" %}
                        <h1 class="mb-0 h3">
                            Lasair Sign In
                        </h1>
                        <br />
                        <p>
                            {% if msg %}
                                <span class="text-danger">{{ msg | safe }}</span>
                            {% endif %}

                        </p>
                    </div>
                    <form method="post" action="" class="mt-4">

                        {% csrf_token %}

                        <!-- Form -->
                        <div class="form-group mb-4">
                            <label for="email">Username</label>
                            <div class="input-group">
                                <span class="input-group-text" id="basic-addon1">
                                    <span class="fas fa-user-circle"></span>
                                </span>
                                {{ form.username|add_class:"form-control" }}
                            </div>
                            <span class="text-error">{{ form.username.errors }}</span>
                        </div>
                        <!-- End of Form -->
                        <div class="form-group">
                            <!-- Form -->
                            <div class="form-group mb-4">
                                <label for="password">Your Password</label>
                                <div class="input-group">
                                    <span class="input-group-text" id="basic-addon2">
                                        <span class="fas fa-unlock-alt"></span>
                                    </span>
                                    {{ form.password|add_class:"form-control" }}
                                </div>
                                <div class="text-error mt-3"> {{ form.non_field_errors }}</div>
                            </div>
                            <!-- End of Form -->
                            <div class="d-flex justify-content-between align-items-top mb-4">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="" id="remember">
                                    <label class="form-check-label mb-0" for="remember">
                                        Remember me
                                    </label>
                                </div>
                                <div><a href="{% url 'password_reset' %}" class="small text-right">Lost password?</a></div>
                            </div>
                        </div>
                        <div class="d-grid">
                            <button type="submit" name="login" class="btn btn-gray-800">Sign In</button>
                        </div>
                    </form>
                    <br />

                    <div class="d-flex justify-content-center align-items-center mt-4">
                        <span class="fw-normal">
                            Not registered?
                            <a href="{% url 'register' %}" class="fw-bold">Create account</a>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

webserver/users/templates/users/logout.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Logged Out {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="container">
        <a href="{% url 'index' %}" class="d-flex align-items-center justify-content-center mt-9 mb-4">
            <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z" clip-rule="evenodd"></path></svg>
            Back to homepage
        </a>
        <div class="row justify-content-center">
            <div class="col-12 d-flex align-items-center justify-content-center">
                <div class="bg-white shadow border-0 rounded p-4 p-lg-5 w-100 fmxw-500">
                    <div class="text-center text-md-center mb-4 mt-md-0">
                        <div class="avatar avatar-lg mx-auto mb-3"><img class="rounded-circle" alt="Image placeholder" src="data:image/png;base64,{{ profile_image }}"></div>
                        <h1 class="h3">{{ username }}</h1>
                        <p class="text-gray">You are now logged out.</p>
                    </div>
                    <form class="mt-5" action='{% url 'login' %}' method=POST>
                        {% csrf_token %}
                        <input type="hidden" id="username" name="username" value="{{ username }}">
                        <!-- Form -->
                        <div class="form-group mb-4">
                            <label for="password">Your Password</label>
                            <div class="input-group">
                                <span class="input-group-text" id="basic-addon2">
                                    <svg class="icon icon-xs text-gray-600" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd"></path></svg>
                                </span>
                                <input type="password" placeholder="Password" class="form-control" id="id_password" required name="password" autocomplete="current-password">

                            </div>
                        </div>
                        <!-- End of Form -->
                        <div class="d-grid mt-3">
                            <button type="submit" name="login" class="btn btn-gray-800">Sign In Again</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

webserver/users/templates/users/password_reset.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Forgot Password {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


    <div class="container">
        <div class="row justify-content-center form-bg-image">

            <div class="col-12 d-flex align-items-center justify-content-center mt-9">
                <div class="signin-inner my-3 my-lg-0 bg-white shadow border-0 rounded p-4 p-lg-5 w-100 fmxw-500">
                    {% include "includes/icons/icon.html" %}
                    <h1 class="h3">Forgot your password?</h1>
                    <p class="mb-4">Don't fret! Just type in your email and we will send you a code to reset your password!</p>
                    <form method="post">
                        {% csrf_token %}
                        <!-- Form -->
                        <div class="mb-4">
                            <label for="email">Your Email</label>
                            <div class="input-group">
                                <input type="email" class="form-control" name="email" id="email" placeholder="john@company.com" required autofocus>
                            </div>
                        </div>
                        <!-- End of Form -->
                        <div class="d-grid">
                            <button type="submit" class="btn btn-gray-800">Recover password</button>
                        </div>
                    </form>

                </div>

            </div>
            <p class="text-center"><a href="{% url 'login' %}" class="d-flex align-items-center justify-content-center mt-4">
                <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z" clip-rule="evenodd"></path></svg>
                Back to log in
            </a>
            </p>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

webserver/users/templates/users/password_reset_confirm.html
{% extends "layouts/base-fullscreen.html" %}
{% load widget_tweaks %}
{% block title %} Reset Password {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


    <div class="container">
        <div class="row justify-content-center form-bg-image mt-9 mb-5">
            <p class="text-center"><a href="{% url 'login' %}" class="d-flex align-items-center justify-content-center">
                <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z" clip-rule="evenodd"></path></svg>
                Back to log in
            </a>
            </p>
            <div class="col-12 d-flex align-items-center justify-content-center">
                <div class="bg-white shadow border-0 rounded p-4 p-lg-5 w-100 fmxw-500">
                    <h1 class="h3 mb-4">Reset password</h1>
                    <form method="post">
                        {% csrf_token %}

                        <!-- Form -->
                        <div class="form-group mb-4">
                            <label for="password">Your Password</label>
                            <div class="input-group">
                                <span class="input-group-text" id="basic-addon2">
                                    <svg class="icon icon-xs text-gray-600" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd"></path></svg>
                                </span>

                                <input type="password" placeholder="Password" class="form-control" name="new_password1" id="password" required>
                            </div>
                            <span class="text-error">{{ form.new_password1.errors }}</span>
                        </div>
                        <!-- End of Form -->
                        <!-- Form -->
                        <div class="form-group mb-4">
                            <label for="confirm_password">Confirm Password</label>
                            <div class="input-group">
                                <span class="input-group-text" id="basic-addon2">
                                    <svg class="icon icon-xs text-gray-600" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd"></path></svg>
                                </span>
                                <input type="password" placeholder="Confirm Password" class="form-control"  name="new_password2" id="confirm_password" required>
                                <span class="text-error">{{ form.new_password1.errors }}</span>
                            </div>
                            <span class="text-error">{{ form.new_password2.errors }}</span>
                        </div>
                        <!-- End of Form -->
                        <div class="d-grid">
                            <button type="submit" class="btn btn-gray-800">Reset password</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

webserver/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
    {% blocktranslate %}You're receiving this email because you requested to set/reset the password for your user account at {{ site_name }}.{% endblocktranslate %}

    {% translate "Please go to the following page and choose a new password:" %}
    {% block reset_link %}
        https://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
    {% endblock %}
    {% translate 'Your username, in case you’ve forgotten, is' %} {{ user.get_username }}

    {% blocktranslate %}The Lasair team{% endblocktranslate %}

{% endautoescape %}

webserver/users/templates/users/profile.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block title %} Profile {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


    <div class="row mt-4 justify-content-center">
        <div class="col-12 col-xl-8 justify-content-center">
            <div class="col-12 col-md-6 col-xxl-5 mb-4 mx-auto">
                <div class="card shadow border-0 text-center p-0 ">
                    <div class="profile-cover rounded-top" data-background="{{ ASSETS_ROOT }}/img/space_images/space_image_002.jpg"></div>
                    <div class="card-body pb-5">
                        <img src="data:image/png;base64,{{ request.user.profile.image_b64 }}" class="avatar-xl rounded-circle mx-auto mt-n7 mb-4" alt="Profile Pic">
                        <h4 class="h3">
                            {{ request.user.first_name }}  {{ request.user.last_name }}
                        </h4>
                        <h5 class="fw-normal">
                            {{ request.user.username }}
                        </h5>
                        <p class="text-gray mb-4">
                            {{ request.user.email }}
                        </p>
                        <p class="fw-bold text-gray  mb-0">API Token</p>
                        <code class="mt-0">{{ token }}</code>

                    </div>
                </div>
            </div>
            <div class="col-12 col-md-10 col-xxl-8 mb-4 mx-auto">
                <div class="card card-body border-0 shadow mb-4">
                    <h2 class="h5 mb-4">Update Your Profile Information</h2>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <div>
                                    {{ u_form.first_name|as_crispy_field}}
                                </div>
                            </div>

                            <div class="col-md-6 mb-3">
                                <div>
                                    {{ u_form.last_name|as_crispy_field}}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6 mb-4">
                                <div class="form-group">
                                    <label for="id_email">Email</label>
                                    <input class="form-control" id="id_email" type="email" name="email"  placeholder="name@company.com" value="{{ request.user.email }}" required readonly>
                                </div>
                                <span class="text-error">{{ u_form.email.errors }}</span>
                            </div>
                            <div class="col-md-6 mb-4">
                                <div class="form-group">
                                    <label for="id_username">Username</label>
                                    <input class="form-control" id="id_username" type="text" name="username"   placeholder="Enter a username" value="{{ request.user.username }}" required>
                                </div>
                                <span class="text-error">{{ u_form.username.errors }}</span>
                            </div>
                        </div>


                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <div class="form-group">
                                    <label for="id_image">Profile Image</label>
                                    <input type="file" name="image" id="id_image" class="form-control">
                                </div>
                                <span class="text-error">{{ p_form.image.errors }}</span>
                            </div>

                            <div class="col-md-6 mb-3">
                                <svg class="icon text-gray-500 me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a3 3 0 00-3 3v4a5 5 0 0010 0V7a1 1 0 112 0v4a7 7 0 11-14 0V7a5 5 0 0110 0v4a3 3 0 11-6 0V7a1 1 0 012 0v4a1 1 0 102 0V7a3 3 0 00-3-3z" clip-rule="evenodd"></path></svg>
                                <div class="text-gray small">Upload a square JPG, GIF or PNG. If the image is not square it is going to get squished!</div>

                            </div>


                        </div>




                    </div>

                    <div class="mt-3 d-flex flex-row-reverse">
                        <button class="btn btn-gray-800 mt-2 animate-up-2" type="submit">Save</button>
                    </div>
                </form>
            </div>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}