webserver/lasair/apps/filter_query/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('filters/', views.filter_query_index, name='filter_query_index'),
    path('filters/create/', views.filter_query_create, name='filter_query_create'),
    path('filters/<int:mq_id>/delete/', views.filter_query_delete, name='filter_query_delete'),
    path('filters/<int:mq_id>/update/', views.filter_query_create, name='filter_query_update'),
    path('filters/<int:mq_id>/', views.filter_query_detail, name='filter_query_detail'),
    path('filters/<int:mq_id>/<slug:action>/', views.filter_query_detail, name='filter_query_detail_run'),
    path('filters/log/(?P<topic>[-a-zA-Z0-9_.]+)/', views.filter_query_log, name='filter_query_log'),
]

webserver/users/urls.py
from django.conf.urls.static import static
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('register/', views.register, name='register'),  # FIX ME
    path('profile/', views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', views.logout, name='logout'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html", post_reset_login=True, success_url="/password-reset/success/"), name='password_reset_confirm'),
    path('password-reset/success/', auth_views.PasswordResetDoneView.as_view(template_name="index.html", extra_context={"alert": "You have successfully changed your password and are now logged in."}), name='password_reset_success'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="users/password_reset.html", email_template_name="users/password_reset_email.html"), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="index.html", extra_context={"alert": "If your email is associated with a registered account, you will receive an email with instructions on how to change your password."}), name='password_reset_done'),
    path('activate/<uidb64>/<token>', views.activate, name='activate')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webserver/lasair/apps/filter_query/models.py
from django.db import models
from django.contrib.auth.models import User


class filter_query(models.Model):
    """The filter/query model. Filters are owned by a 'User'
    """

    mq_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, models.DO_NOTHING, db_column='user', blank=True, null=True)
    name = models.CharField(max_length=256, blank=True, null=True)
    description = models.CharField(max_length=4096, blank=True, null=True)
    selected = models.CharField(max_length=4096, blank=True, null=True)
    conditions = models.CharField(max_length=4096, blank=True, null=True)
    tables = models.CharField(max_length=4096, blank=True, null=True)
    public = models.BooleanField(blank=True, null=True)
    active = models.IntegerField(blank=True, null=True)
    topic_name = models.CharField(max_length=256, blank=True, null=True)
    real_sql = models.CharField(max_length=4096, blank=True, null=True)
    date_created  = models.DateTimeField(auto_now_add=True, editable=False, blank=True, null=True)
    date_modified = models.DateTimeField(auto_now=    True, editable=False, blank=True, null=True)
    date_expire   = models.DateTimeField(                   editable=True,  blank=True, null=True)


    class Meta:
        """Meta.
        """

        managed = True
        db_table = 'myqueries'

    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name + ': ' + self.name

webserver/lasair/apps/filter_query/views.py
from .utils import add_filter_query_metadata, run_filter, topic_name, check_query_zero_limit, delete_stream_file, topic_refresh
import random
from src import date_nid, db_connect
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from lasair.apps.annotator.models import Annotators
from lasair.apps.watchmap.models import Watchmap
from lasair.apps.watchlist.models import Watchlist
from confluent_kafka import Producer, KafkaError, admin
from django.views.decorators.csrf import csrf_exempt
from lasair.apps.db_schema.utils import get_schema, get_schema_dict, get_schema_for_query_selected
from .models import filter_query
from .forms import filterQueryForm, UpdateFilterQueryForm, DuplicateFilterQueryForm
from lasair.query_builder import check_query, build_query
from django.conf import settings
import json
import re
import copy
import time
import datetime
from django.contrib import messages
import os
import sys
import sqlparse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
sys.path.append('../common')


@csrf_exempt
def filter_query_index(request):
    """*Return list of all filter queries viewable by user*

    **Key Arguments:**

    - `request` -- the original request

    **Usage:**

    ```python
    urlpatterns = [
        ...
        path('filters/', views.filter_query_index, name='filter_query_index'),
        ...
    ]
    ```
    """

    # PUBLIC FILTERS
    publicFilters = filter_query.objects.filter(public__gte=1)
    publicFilters = add_filter_query_metadata(publicFilters, remove_duplicates=True)

    # USER FILTERS
    if request.user.is_authenticated:
        myFilters = filter_query.objects.filter(user=request.user)
        myFilters = add_filter_query_metadata(myFilters)
    else:
        myFilters = None

    return render(request, 'filter_query/filter_query_index.html',
                  {'myFilters': myFilters,
                   'publicFilters': publicFilters,
                   'authenticated': request.user.is_authenticated})


def filter_query_detail(request, mq_id, action=False):
    """*return the result of a filter query*

    **Key Arguments:**

    - `request` -- the original request
    - `mq_id` -- the filter UUID
    - `run` -- run filter

    **Usage:**

    ```python
    urlpatterns = [
        ...
        path('filters/<int:mq_id>/', views.filter_query_detail, name='filter_query_detail'),
        ...
    ]
    ```
    """

    # CONNECT TO DATABASE AND GET FILTER
    msl = db_connect.readonly()
    cursor = msl.cursor(buffered=True, dictionary=True)
    filterQuery = get_object_or_404(filter_query, mq_id=mq_id)
    filterQuery.real_sql = build_query(filterQuery.selected, filterQuery.tables, filterQuery.conditions)

    # IS USER ALLOWED TO SEE THIS RESOURCE?
    is_owner = (request.user.is_authenticated) and (request.user.id == filterQuery.user.id)
    is_public = (filterQuery.public > 0)
    is_visible = is_owner or is_public
    if not is_visible:
        messages.error(request, "This filter is private and not visible to you")
        return render(request, 'error.html')

    if request.method == 'POST':
        form = UpdateFilterQueryForm(request.POST, instance=filterQuery, request=request)
        duplicateForm = DuplicateFilterQueryForm(request.POST, instance=filterQuery, request=request)
        action = request.POST.get('action')

    if request.method == 'POST' and is_owner and action == 'save':

        # UPDATING SETTINGS?
        if action == 'save' and form.is_valid():
            # UPDATING SETTINGS?
            filterQuery.name = request.POST.get('name')
            filterQuery.description = request.POST.get('description')

            if request.POST.get('active'):
                filterQuery.active = int(request.POST.get('active'))
            else:
                filterQuery.active = 0

            if request.POST.get('public'):
                filterQuery.public = 1
            else:
                filterQuery.public = 0

            filterQuery.date_expire = \
                    datetime.datetime.now() + datetime.timedelta(days=settings.ACTIVE_EXPIRE)

            # REFRESH STREAM
            message = ''
            tn = topic_name(request.user.id, filterQuery.name)
            filterQuery.topic_name = tn
            delete_stream_file(request, filterQuery.name)
            if filterQuery.active == 2:
                try:
                    message = topic_refresh(filterQuery.real_sql, tn, limit=10)
                except Exception as e:
                    messages.error(request, f'The kafka topic could not be refreshed for this filter. {e}')
            filterQuery.save()
            if len(message) == 0:
                messages.success(request, f'Your filter has been successfully updated')
            else:
                messages.success(request, message)
    elif request.method == 'POST' and action == 'copy' and duplicateForm.is_valid():

        oldName = copy.deepcopy(filterQuery.name)
        name = request.POST.get('name')
        description = request.POST.get('description')
        newFil = filterQuery
        newFil.pk = None
        newFil.user = request.user
        newFil.name = request.POST.get('name')
        newFil.description = request.POST.get('description')
        newFil.active = request.POST.get('active')

        if request.POST.get('public'):
            newFil.public = True
        else:
            newFil.public = False

        newFil.date_expire = \
            datetime.datetime.now() + datetime.timedelta(days=settings.ACTIVE_EXPIRE)

        newFil.save()
        filterQuery = newFil
        mq_id = filterQuery.pk

        messages.success(request, f'You have successfully copied the "{oldName}" filter to My Filters. The results table is initially empty, but should start to fill as new transient detections match against your filter.')
        return redirect(f'filter_query_detail', mq_id)
    else:
        form = UpdateFilterQueryForm(instance=filterQuery, request=request)
        duplicateForm = DuplicateFilterQueryForm(instance=filterQuery, request=request)

    filterQuery = get_object_or_404(filter_query, mq_id=mq_id)

    filterQuery.real_sql = build_query(filterQuery.selected, filterQuery.tables, filterQuery.conditions)

    cursor.execute(f'SELECT name, selected, tables, conditions, real_sql FROM myqueries WHERE mq_id={mq_id}')
    for row in cursor:
        query_name = row['name']
        selected = row['selected']
        tables = row['tables']
        conditions = row['conditions']
        real_sql = row['real_sql']
        filterQuery.real_sql = sqlparse.format(filterQuery.real_sql, reindent=True, keyword_case='upper', strip_comments=True)

    limit = 1000
    offset = 0
    count = None
    table = {}
    schema = {}

    if action == "run":
        table, schema, count, topic, error = run_filter(
            selected=filterQuery.selected,
            tables=filterQuery.tables,
            conditions=filterQuery.conditions,
            limit=limit,
            offset=offset,
            mq_id=mq_id,
            query_name=filterQuery.name)
        if error:
            messages.error(request, error)

    if count and count == limit:
        if settings.DEBUG:
            apiUrl = "https://lasair.readthedocs.io/en/develop/core_functions/rest-api.html"
        else:
            apiUrl = "https://lasair.readthedocs.io/en/main/core_functions/rest-api.html"
        messages.info(request, f"We are only displaying the first <b>{limit}</b> objects matched against this filter. But don't worry! You can access all results via the <a class='alert-link' href='{apiUrl}' target='_blank'>Lasair API</a>.")
    else:
        limit = False

    if "order by" in filterQuery.real_sql.lower():
        sortTable = False
    else:
        sortTable = True

    return render(request, 'filter_query/filter_query_detail.html', {
        'filterQ': filterQuery,
        'table': table,
        'count': count,
        "schema": schema,
        "form": form,
        "duplicateForm": duplicateForm,
        'limit': str(limit),
        'sortTable': sortTable
    })


@login_required
def filter_query_create(request, mq_id=False):
    """*create or update a filter*

    **Key Arguments:**

    - `request` -- the original request
    - `mq_id` -- the fitler query ID (if updating an existing filter)

    **Usage:**

    ```python
    urlpatterns = [
        ...
        path('filters/create/', views.filter_query_create, name='filter_query_create'),
        path('filters/<int:mq_id>/update/', views.filter_query_create, name='filter_query_update')
        ...
    ]
    ```
    """
    message = ''

    # BUILD CONTENT FOR THE CREATION FORM
    schemas_core = {
        'objects': get_schema('objects'),
        'crossmatch_tns': get_schema('crossmatch_tns'),
        'sherlock_classifications': get_schema('sherlock_classifications')
    }
    schemas_addtional = {
        'watchlist_hits': get_schema('watchlist_hits'),
        'annotations': get_schema('annotations'),
    }

    filterQuery = None

    if request.method == 'POST' or mq_id:
        if request.method == 'POST':
            if mq_id:
                filterQuery = get_object_or_404(filter_query, mq_id=mq_id)
                form = filterQueryForm(request.POST, request=request, instance=filterQuery)
            else:
                form = filterQueryForm(request.POST, request=request)
            # COLLECT FORM CONTENT
            action = request.POST.get('action')
            selected = request.POST.get('selected')
            conditions = request.POST.get('conditions')
            watchlists = request.POST.get('watchlists')
            watchmaps = request.POST.getlist('watchmaps')
            annotators = request.POST.getlist('annotators')
            name = request.POST.get('name')
            description = request.POST.get('description')

webserver/lasair/apps/filter_query/templates/filter_query/filter_query_create.html
{% extends "layouts/base.html" %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}
{% load static %}


{% block title %}
    {{data.objectId}}
{% endblock title %}


{% block content %}



    <div class="container">

        <div class="row mt-4">

            <div class="col-12 mb-4">
                {% include "includes/widgets/widget_filter_query_create_header.html"  %}
            </div>


            <div class="col-12 mb-4">
                {% include "includes/widgets/widget_filter_creation_form.html" %}
            </div>
            <div class="col-12 mb-4">
                {% include "includes/widgets/widget_objectlist_table.html" with zerotext="Zero objects have been matched against this filter so far. Check back later to see if any new objects have been matched, or amend the filtering criteria to catch more objects." table=table header="Filter Results"  desc="Here are the filtered objects, limited to "|add:limit|add:" objects" real_sql=real_sql  sortTable=sortTable  %}
            </div>








        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
    <script>

        function updateAutocomplete(){

            // NEED TO REMOVE PRISM LIVE AND REINSTATE AT THE END OF THIS FUNCTION FOR TAB COMPLETE TO WORK
            document.querySelectorAll("div.prism-live").forEach(el=>el.replaceWith(el.querySelector("textarea.prism-live")));

            // QUICKEST CLEANEST WAY TO REGENERATE AUTOCOMPLETES
            var old_element = document.querySelector("textarea#id_conditions");
            var new_element = old_element.cloneNode(true);
            old_element.parentNode.replaceChild(new_element, old_element);

            var old_element = document.querySelector("textarea#id_selected");
            var new_element = old_element.cloneNode(true);
            old_element.parentNode.replaceChild(new_element, old_element);

            // DEFAULT, ALWAYS PRESENT AUTOCOMPLETE
            var justTypeCollectionValues = [
                { key : "MYSQL > jdnow", value: "jdnow()", info: "The current time in Julian Days"},
                { key : "MYSQL > as", value: "as", info: false},
                { key : "MYSQL > BETWEEN", value: "BETWEEN xx AND xx", info: ""},
                { key : "MYSQL > LIKE", value: "LIKE '%xx%'", info: ""}
            ];
            var tableColumns = [];
            {% for schema_name, schema_content in schemas_core.items %}
                justTypeCollectionValues.push({ key : "TABLE > {{schema_name}}", value: "{{schema_name}}", info: ""})
                var theseColumns = {
                    trigger: "{{schema_name}}".concat("."),
                    values: [],
                    noMatchTemplate: "",
                    spaceSelectsMatch: false,
                    selectTemplate: function(item) {
                        return item.original.value;
                    },
                    menuItemTemplate: function(item) {
                        if (item.original.info.length > 0) {
                            return item.string + `{% include "includes/info_tooltip.html" with info="`+item.original.info+`" position="top" %}`;
                        } else {
                            return item.string
                        }

                    }
                }

                {% for row in schema_content %}
                    theseColumns.values.push({ key : "COLUMN > {{schema_name}}.{{row.name}}", value: "{{schema_name}}.{{row.name}}", info: "{{row.doc}}"})
                {% endfor %}
                tableColumns.push(theseColumns)
            {% endfor %}

            var e = document.getElementById("id_watchlists");
            if (e.value) {
                justTypeCollectionValues.push({ key : "TABLE > watchlist_hits", value: "watchlist_hits", info: ""})
                var theseColumns = {
                    trigger: "watchlist_hits.",
                    values: [],
                    noMatchTemplate: "",
                    spaceSelectsMatch: false,
                    selectTemplate: function(item) {
                        return item.original.value;
                    },
                    menuItemTemplate: function(item) {
                        if (item.original.info.length > 0) {
                            return item.string + `{% include "includes/info_tooltip.html" with info="`+item.original.info+`" position="top" %}`;
                        } else {
                            return item.string
                        }

                    }
                }
                {% for row in schemas_additional.watchlist_hits %}
                    theseColumns.values.push({ key : "COLUMN > watchlist_hits.{{row.name}}", value: "watchlist_hits.{{row.name}}", info: "{{row.doc}}"})
                {% endfor %}
                tableColumns.push(theseColumns)
            }

            // ANNOTATORS
            var avalues = document.getElementById("id_annotators").selectedOptions;
            for (i = 0; i < avalues.length; i++) {
                justTypeCollectionValues.push({ key : "TABLE > ".concat(avalues[i].value), value: avalues[i].value, info: "{{row.doc}}"})
                var theseColumns = {
                    trigger:  avalues[i].value.concat("."),
                    values: [],
                    noMatchTemplate: "",
                    spaceSelectsMatch: false,
                    selectTemplate: function(item) {
                        return item.original.value;
                    },
                    menuItemTemplate: function(item) {
                        if (item.original.info.length > 0) {
                            return item.string + `{% include "includes/info_tooltip.html" with info="`+item.original.info+`" position="top" %}`;
                        } else {
                            return item.string
                        }

                    }
                }
                {% for row in schemas_additional.annotations %}
                    theseColumns.values.push({ key : "COLUMN > ".concat(avalues[i].value,".{{row.name}}"), value: avalues[i].value.concat(".{{row.name}}"), info: "{{row.doc}}"})
                {% endfor %}
                tableColumns.push(theseColumns)
            }

            var justTypeCollection = {
                values: justTypeCollectionValues,
                selectTemplate: function(item) {
                    if (item.original.key.includes("MYSQL >")) {
                        return item.original.value+" ";

                    } else {
                        return item.original.value+".";
                    }

                },
                menuItemTemplate: function(item) {
                    if (item.original.info.length > 0) {
                        return item.string + `{% include "includes/info_tooltip.html" with info="`+item.original.info+`" position="top" %}`;
                    } else {
                        return item.string
                    }

                }
            };

            var tributeAutocompleteSelectArea = new Tribute({
                autocompleteMode: true,
                noMatchTemplate: "",
                spaceSelectsMatch: false,
                replaceTextSuffix: '',
                collection: [justTypeCollection]
            });

            tributeAutocompleteSelectArea.attach(
                document.querySelector("textarea#id_selected")
            );
            tributeAutocompleteSelectArea.attach(
                document.querySelector("textarea#id_conditions")
            );

            var tributeAutocompleteTestAreaColumns = new Tribute({
                noMatchTemplate: "",
                collection: tableColumns
            });
            tributeAutocompleteTestAreaColumns.attach(
                document.querySelector("textarea#id_selected")
            );
            tributeAutocompleteTestAreaColumns.attach(
                document.querySelector("textarea#id_conditions")
            );


            document.querySelector("textarea#id_selected").addEventListener('keydown', function(e) {
                updateFrom()
                if (e.key == 'Tab') {
                    if (tributeAutocompleteSelectArea.isActive | tributeAutocompleteTestAreaColumns.isActive) {
                        e.stopImmediatePropagation()
                    }
                }

            });
            document.querySelector("textarea#id_conditions").addEventListener('keydown', function(e) {
                if (e.key == 'Tab') {
                    if (tributeAutocompleteSelectArea.isActive | tributeAutocompleteTestAreaColumns.isActive) {
                        e.stopImmediatePropagation()
                    }
                }
            });

            let prismEditor = new Prism.Live(document.getElementById("id_selected"));
            let prismEditor2 = new Prism.Live(document.getElementById("id_conditions"));
            updateFrom();
        };






        function updateFrom(){
            var selectText = document.getElementById('id_selected').value;
            var tableList = [ '{{ schemas_core.keys|join:"', '" }}' ];
            var fromContent = new Array();
            for (i = 0; i < tableList.length; i++) {
                var table = tableList[i];
                if (selectText.indexOf(table+".") >= 0) {
                    fromContent.push(table);
                }
            }

            var e = document.getElementById("id_watchlists");
            if (e.value) {
                fromContent.push("'".concat(e.options[e.selectedIndex].text.replace(/ *\([^)]*\) */g, ""),"' as watchlist_hits"));
        }

        var values = document.getElementById("id_watchmaps").selectedOptions;
        for (i = 0; i < values.length; i++) {
            fromContent.push(values[i].text.replace(/ *\([^)]*\) */g, "").concat(" (watchmap)"));
        }

        var values = document.getElementById("id_annotators").selectedOptions;
        for (i = 0; i < values.length; i++) {
            fromContent.push(values[i].text.replace(/ *\([^)]*\) */g, "").concat(" (annotator)"));
        }


        // ARRAY TO COMMA SEPARATED LIST
        fromContent = fromContent.toString().replaceAll(",",", ");
        document.getElementById("from_box").innerHTML = fromContent;

        };

        document.addEventListener('DOMContentLoaded', function() {
            updateAutocomplete();

        }, false);


        $(document).ready(function () {
            $('#id_watchlists').multiselect({
                buttonClass: 'form-select',
                nonSelectedText: 'None selected',
                maxHeight: 500,
                numberDisplayed: 2,
                enableCaseInsensitiveFiltering: true,
                templates: {
                    button: '<button type="button" class="multiselect dropdown-toggle" data-bs-toggle="dropdown"><span class="multiselect-selected-text"></span></button>',
                },
                onChange: function() {
                    updateAutocomplete();
                }
            });
        });

        $(document).ready(function () {
            $('#id_watchmaps').multiselect({
                buttonClass: 'form-select',

                maxHeight: 500,
                numberDisplayed: 2,
                enableCaseInsensitiveFiltering: true,
                templates: {
                    button: '<button type="button" class="multiselect dropdown-toggle" data-bs-toggle="dropdown"><span class="multiselect-selected-text"></span></button>',
                },
                nonSelectedText: 'No Watchmap Selected',
                onChange: function() {
                    updateAutocomplete();
                }
            });
        });

        $(document).ready(function () {
            $('#id_annotators').multiselect({
                buttonClass: 'form-select',
                buttonWidth: '300px',
                maxHeight: 500,
                numberDisplayed: 2,
                enableCaseInsensitiveFiltering: true,
                templates: {
                    button: '<button type="button" class="multiselect dropdown-toggle" data-bs-toggle="dropdown"><span class="multiselect-selected-text"></span></button>',
                },
                nonSelectedText: 'No Annotator Selected',
                onChange: function() {
                    updateAutocomplete();
                }
            });
        });

        {% if form.errors and not form.selected.errors %}
            $(document).ready(function(){
                $("#editFilterForm").modal('show');
            });
        {% endif %}


        var body = $('body');
        body.on('mouseover', '[data-bs-toggle="tooltip"]', function (e) {
            e.stopPropagation();
            return new bootstrap.Tooltip(this).show();
        });

        body.on('mouseleave', '[data-bs-toggle="tooltip"]', function (e) {
            $('[role="tooltip"]').fadeOut(function () {
                e.stopPropagation();
                $(this).remove();
            });
        });


    </script>
{% endblock javascripts %}

webserver/lasair/apps/filter_query/templates/filter_query/filter_query_detail.html
{% extends "layouts/base.html" %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}
{% load static %}


{% block title %}
    Filter: {{ filterQ.name }}
{% endblock title %}


{% block content %}



    <div class="container">

        <div class="row mt-4">

            <div class="row mt-4">

                <div class="col-12 mb-4">
                    {% include "includes/widgets/widget_filter_query_header.html" with real_sql=filterQ.real_sql %}
                </div>

                {% if limit and limit != "False" %}
                    <div class="col-12 mb-4">
                        {% include "includes/widgets/widget_objectlist_table.html" with zerotext="Zero objects have been matched against this filter so far. Check back later to see if any new objects have been matched, or amend the filtering criteria to catch more objects." table=table header="Filter Results"  desc="A list of objects passing the '"|add:filterQ.name|add:"' filter, capped at "|add:limit|add:" objects."  sortTable=sortTable %}
                    </div>
                {% elif 'run' in request.path %}


                    <div class="col-12 mb-4">
                        {% include "includes/widgets/widget_objectlist_table.html" with zerotext="Zero objects have been matched against this filter so far. Check back later to see if any new objects have been matched, or amend the filtering criteria to catch more objects." table=table header="Filter Results"  desc="A list of objects passing the '"|add:filterQ.name|add:"' filter."  export_name=filterQ.topic_name|add:"_filter_results" sortTable=sortTable %}
                    </div>
                {% else %}
                    <div class="col-12 mb-4">
                        {% include "includes/widgets/widget_objectlist_table.html" with zerotext="Click on the run button above to execute your filter." table=table header="Filter Results"  desc="A list of objects passing the '"|add:filterQ.name|add:"' filter."  export_name=filterQ.topic_name|add:"_filter_results"  sortTable=sortTable %}
                    </div>


                {% endif %}

            </div>
        </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

    <script>
        {% if form.name.errors %}
            $(document).ready(function(){
                $("#editFilterForm").modal('show');
            });
        {% endif %}

        {% if duplicateForm.name.errors %}
            $(document).ready(function(){
                $("#duplicateFilterForm").modal('show');
            });
        {% endif %}
    </script>

{% endblock javascripts %}